### ISSUE TITLE
Still needed after latest semgrep?

### ISSUE THREAD

**Issue by aryx** [navhits/semgrep-precommit#1]
Hi @navhits 
We recently upgraded semgrep to support diff-aware in precommit.
See https://github.com/returntocorp/semgrep/pull/7973
Do you think it covers your use-case?

**Comment by navhits** [comment]
Hi @aryx,
Thanks for the inclusion. This is great! We may not require this repo/hook, and I'll archive the repo. Before that, I want to clarify one thing. I see the docs/changelogs mention the usage of `semgrep ci` command for pre-commit hooks. Does it not work with `semgrep scan` by setting `baseline-ref` or the environment variable?

**Comment by navhits** [comment]
Ps. Using git worktree is much better and faster. This is great!

**Comment by ajbt200128** [comment]
@navhits it also works with just normal semgrep scan!

**Comment by navhits** [comment]
Thanks @ajbt200128. I haven't tried this feature yet, but saw the implementation. It looks neat. I'll archive this repo after adding a link to this PR in the readme.
